import type { Metadata } from "next";
import { PropsWithChildren, Suspense } from "react";
import Loading from "./(templates)/loading";
import AuthDataWrapper from "./_components/auth/AuthDataWrapper";
import Providers from "./_libs/contexts/Providers";
import ContentLayout from "./ContentLayout";
import "./globals.css";

export const metadata: Metadata = {
  title: "TheBlueApp",
  description: "Generated by create next app",
};

export default async function RootLayout({
  modal,
  children,
}: PropsWithChildren<{
  modal: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="font-roboto h-full bg-background-primary text-text-primary overscroll-y-none"
    >
      <body className="relative w-full h-full overscroll-none">
        <Providers>
          <Suspense fallback={<Loading />}>
            <AuthDataWrapper>
              <ContentLayout>
                {modal}
                {children}
              </ContentLayout>
            </AuthDataWrapper>
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
