// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: comment.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (content, user_id, post_id)
    VALUES ($1, $2, $3)
RETURNING
    id, created_at, content, user_id, post_id
`

type CreateCommentParams struct {
	Content string `json:"content"`
	UserID  int64  `json:"user_id"`
	PostID  int64  `json:"post_id"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (*Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.Content, arg.UserID, arg.PostID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Content,
		&i.UserID,
		&i.PostID,
	)
	return &i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, commentID int64) error {
	_, err := q.db.Exec(ctx, deleteComment, commentID)
	return err
}

const getPaginatedCommentsByPostID = `-- name: GetPaginatedCommentsByPostID :many
SELECT
    c.created_at AS created_at,
    c.id AS comment_id,
    c.content AS content,
    COALESCE(t.like_count, 0) AS likes_count,
    (l.id IS NOT NULL)::bool AS has_liked,
    u.username AS owner_username,
    u.id AS owner_id,
    pr.name AS owner_name,
    pr.profile_image AS owner_profile_image
FROM
    comments c
    LEFT JOIN posts po ON po.id = c.post_id
    LEFT JOIN (
        SELECT
            comment_id,
            COUNT(*) AS like_count
        FROM
            comment_likes
        GROUP BY
            comment_id) t ON c.id = t.comment_id
    LEFT JOIN comment_likes l ON l.comment_id = c.id
        AND l.user_id = $1
    LEFT JOIN users u ON c.user_id = u.id
    LEFT JOIN profiles pr ON u.id = pr.user_id
WHERE
    po.id = $2
ORDER BY
    c.created_at DESC OFFSET $3
LIMIT $4
`

type GetPaginatedCommentsByPostIDParams struct {
	MyUserID int64 `json:"my_user_id"`
	PostID   int64 `json:"post_id"`
	Offset   int32 `json:"offset"`
	Limit    int32 `json:"limit"`
}

type GetPaginatedCommentsByPostIDRow struct {
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CommentID         int64              `json:"comment_id"`
	Content           string             `json:"content"`
	LikesCount        int64              `json:"likes_count"`
	HasLiked          bool               `json:"has_liked"`
	OwnerUsername     *string            `json:"owner_username"`
	OwnerID           *int64             `json:"owner_id"`
	OwnerName         *string            `json:"owner_name"`
	OwnerProfileImage uuid.UUID          `json:"owner_profile_image"`
}

func (q *Queries) GetPaginatedCommentsByPostID(ctx context.Context, arg GetPaginatedCommentsByPostIDParams) ([]*GetPaginatedCommentsByPostIDRow, error) {
	rows, err := q.db.Query(ctx, getPaginatedCommentsByPostID,
		arg.MyUserID,
		arg.PostID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetPaginatedCommentsByPostIDRow
	for rows.Next() {
		var i GetPaginatedCommentsByPostIDRow
		if err := rows.Scan(
			&i.CreatedAt,
			&i.CommentID,
			&i.Content,
			&i.LikesCount,
			&i.HasLiked,
			&i.OwnerUsername,
			&i.OwnerID,
			&i.OwnerName,
			&i.OwnerProfileImage,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
