// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateImages implements pgx.CopyFromSource.
type iteratorForCreateImages struct {
	rows                 []CreateImagesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateImages) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateImages) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Uid,
		r.rows[0].PostID,
	}, nil
}

func (r iteratorForCreateImages) Err() error {
	return nil
}

func (q *Queries) CreateImages(ctx context.Context, arg []CreateImagesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"post_images"}, []string{"uid", "post_id"}, &iteratorForCreateImages{rows: arg})
}
