// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Content   string             `json:"content"`
	UserID    int64              `json:"user_id"`
	PostID    int64              `json:"post_id"`
}

type CommentLike struct {
	ID        int64 `json:"id"`
	CommentID int64 `json:"comment_id"`
	UserID    int64 `json:"user_id"`
}

type Follower struct {
	ID         int64 `json:"id"`
	FollowerID int64 `json:"follower_id"`
	FolloweeID int64 `json:"followee_id"`
}

type Post struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Content   *string            `json:"content"`
	UserID    int64              `json:"user_id"`
}

type PostImage struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Uid       uuid.UUID          `json:"uid"`
	PostID    int64              `json:"post_id"`
}

type PostLike struct {
	ID     int64 `json:"id"`
	PostID int64 `json:"post_id"`
	UserID int64 `json:"user_id"`
}

type Profile struct {
	ID           int64              `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Name         string             `json:"name"`
	UserID       int64              `json:"user_id"`
	ProfileImage uuid.UUID          `json:"profile_image"`
}

type User struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	Username  string             `json:"username"`
}

type UserProfileSearch struct {
	UserID       int64       `json:"user_id"`
	Username     string      `json:"username"`
	Name         *string     `json:"name"`
	ProfileImage uuid.UUID   `json:"profile_image"`
	SearchParam  interface{} `json:"search_param"`
}
